### ISSUE TITLE
better-sqlite3 7.1.4 breaks transactions

### ISSUE THREAD

**Issue by jhalag** [Kauto/better-sqlite3-helper#14]
Using the example: runs with no errors if `better-sqlite3@7.1.2` is installed. `better-sqlite3@7.1.4` also runs fine for it's portion of the test, however better-sqlite3-helper fails with an error (shown below).

I don't believe the issue to be (entirely?) on the part of `better-sqlite3`, as it's own equivalent of the same call generates no errors. However as I have not been able to trace the error deeper at this point, I cannot say for certain.

This error appeared in (otherwise working) production code after an update.

### Test Case:
```js
try {
  console.log('test case 1 (better-sqlite3)');
  db = require('better-sqlite3')('./test.db');
  b = db.transaction((obj) => {return null;});
} catch (e) {
  console.error(e);
} finally {
  console.log('test case 1 finished.');
}

try {
  console.log('test case 2 (better-sqlite3-helper)')
  db2 = require('better-sqlite3-helper')({path: './test2.db'});
  b = db2.transaction((obj) => {return null;});
} catch (e) {
  console.error(e);
} finally {
  console.log('test case 2 finished.');
}

```

### Results with `better-sqlite3@7.1.4` installed:
```
test case 1 (better-sqlite3)
test case 1 finished.
test case 2 (better-sqlite3-helper)
TypeError: Cannot read property 'prepare' of undefined
    at getController (.../node_modules/better-sqlite3/lib/methods/transaction.js:35:15)
    at DB.transaction (.../node_modules/better-sqlite3/lib/methods/transaction.js:9:21)
    at Object.<anonymous> (.../testbreak.js:14:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
test case 2 finished.
```
### Results with `better-sqlite3@7.1.2` installed:
```
test case 1 (better-sqlite3)
test case 1 finished.
test case 2 (better-sqlite3-helper)
test case 2 finished.
```

**Comment by jhalag** [comment]
PR submitted. The latest update of the transaction method in `better-sqlite-3` expects `this` to refer to itself. Fix does not appear to cause a regression if 7.1.2 is used instead.

**Comment by Kauto** [comment]
Thank you very much.
